name: release

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

# Make sure the GITHUB_TOKEN has permission to upload to our releases
permissions:
  contents: write

jobs:

  assets:
    runs-on: ubuntu-latest
    #if: ${{ (github.event.workflow_run.conclusion == 'success') && (github.event.release.tag_name != '') }}
    if: ${{ (github.event.workflow_run.conclusion == 'success') }}

    steps:

      - name: Download artifacts
        uses: actions/download-artifact@v6
        with:
          pattern: binaries-*
          path: artifacts/
          # run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: '📦 Publish packages'
        # if:  ${{ startsWith(github.event.release.tag_name, 'rel-') }}
        run: |
          cd ${{github.workspace}}
          mkdir -p build
          find artifacts/ build/ -ls
          env -C artifacts/binaries-linux-x64  zip -r ../../build/ubuntu-amd64.zip        bin/ man/
          env -C artifacts/binaries-macos      zip -r ../../build/macos-arm64.zip         bin/ man/
          env -C artifacts/binaries-linux-x64  zip -r ../../build/linux-static-amd64.zip  bin/ man/
          env -C artifacts/binaries-win-x64    zip -r ../../build/win32-x64.zip           bin/
          env -C artifacts/binaries-win-x86    zip -r ../../build/win32-x86.zip           bin/
          [ -n "${{github.event.release.tag_name}}" ] && refname="${{github.event.release.tag_name}}" || refname="${{github.ref_name}}"
          gh release upload "$refname" build/ubuntu-amd64.zip
          gh release upload "$refname" build/linux-static-amd64.zip
          gh release upload "$refname" build/macos-arm64.zip
          gh release upload "$refname" build/win32-x64.zip
          gh release upload "$refname" build/win32-x86.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash

